version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
  worker:
    build: ./worker
    depends_on:
      - redis
  master:
    build: ./master
    depends_on:
      - redis